#!/usr/bin/python

# Project Euler Problem 2
# Each new term in the Fibonacci sequence is 
# generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose 
# values do not exceed four million, 
# find the sum of the even-valued terms.


a = 2
b = 8
sum = a + b

while True:
    temp = b
    b = a + 4*b
    a = temp

    if b < 4000000:
        sum = sum + b
    else:
        print sum
        break
